### ISSUE TITLE
pgnAnalysis/gameAnalysis error "object 'pgn' not found"

### ISSUE THREAD

**Issue by Hax2kon** [oganm/stockfisher#5]
Hi, I've been appreciating this project a lot!

There is a part of the code in pgnAnalysis that produces an error, because it needs a pgn that is never provided. This part:

`if ("character" %in% class(game)) {
        game <- rchess::Chess$new()
        game$load_pgn(pgn)
}`

How about changing the argument "game" to "pgn", and make the according changes in the script. For example:

`gameAnalysis = function(pgn, movetime=5000, depth = NULL,stockfish = NULL){
...
  if('character' %in% class(pgn)){
    game <- Chess$new()
    game$load_pgn(pgn)
  }`

**Comment by oganm** [comment]
Didn't want to name it `pgn` because the input could be an `rchess` board as well. The `game` argument should work correctly now though. It used to be named pgn though, hence the error...

Note that gameAnalysis currently gives the score based on the next best possible move (see #4). I can't think of a situation where there would be a huge difference between the two but then I am not that well versed in chess. You might see some changes after a fix.

**Comment by Hax2kon** [comment]
Agree, `pgn` is probably an unwise name for the argument. Great that it is solved :)

I'm not really versed in chess either. In a sense, one could argue that the score of the best possible move _is_ the score of the position. I'm not really sure how stockfish calculates scores. Because if one does as suggested and move back to t-1, finds the move that was made and grab the score from this, isn't this score based on the best possible move from that position, which in effect is the score in t?

**Comment by oganm** [comment]
So my understanding is, each board state has a score based on possible futures available to the board, every turn you are trying to switch to the best state possible.

When the engine gives a score based on a possible future move, it is giving a score for a state that never existed on board. For stuff like blunder detection you would want to compare the move that was made with other possible moves which some other UIs that uses stockfish to analyze games seems to be doing. 

The score of the current board will be inevitably correlated with the available best move of course so it should be fine to use this to see how the game is going in general. I didn't get to play around with it too much myself yet. Not sure what kind of issues it'll come across or what are the norms used by everyone else
